# Generated by Django 5.0.6 on 2024-06-26 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='subject',
        ),
    ]
